# rf 后端公共生产 Nacos 配置样例
# Data ID: common-backend-prod.properties
# Group: config
# Namespace: 复用 zy_qy 的 ns-qy-appconf

# JSON 时间格式
spring.jackson.time-zone=Asia/Shanghai
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# Dubbo 公共注册中心
dubbo.registry.address=nacos://nacos.prod.svc.cluster.local:8848

# XXL-JOB 公共调度中心
xxl.job.admin.addresses=http://xxl-job-admin.prod.svc.cluster.local:8080/xxl-job-admin
xxl.job.executor.logpath=${LOG_PATH:${user.home}/logs/${spring.application.name}}/xxl-job
xxl.job.executor.logretentiondays=30

# 配置密文解密
qy.config-crypto.enabled=true
